source 'https://rubygems.org'

ruby "1.9.3"

gem 'rails', '3.2.13'
gem 'validates_timeliness'
gem 'rails_config'
gem 'rb-readline'
gem 'haml'
gem 'simple_form'
gem 'thin'
gem 'missing_validators'
gem "therubyracer"
gem "less-rails"
gem 'twitter-bootstrap-rails'

group :test do
  gem 'timecop'
  gem 'rspec-rails'
  gem 'fabrication'
  gem 'shoulda'
  gem 'forgery'
  gem 'fakeweb'
end

group :assets do
  gem 'therubyracer'
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

